### ISSUE TITLE
Slider labels

### ISSUE THREAD

**Issue by rolandschuetz** [Sebobo/Shel.Neos.RangeEditor#2]
I would like to be able to set labels for min and max, like thi
<img width="312" alt="Bildschirmfoto 2021-10-25 um 12 59 44" src="https://user-images.githubusercontent.com/735982/138683923-39276fa4-11ef-4145-9244-db4456b24dea.png">
s:

**Comment by rolandschuetz** [comment]
Could you make a new release

**Comment by Sebobo** [comment]
Just released it in 1.1.1
